[package]
name = "rust-ws"
version = "0.1.0"
edition = "2018"

[dependencies]
sha1 = { version = "0.6.0", optional = true }
base64 = { version = "0.13.0", optional = true }

[features]
websocket_key = ["sha1", "base64"]